// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: `mysql://${process.env.DATABASE_USER || "root"}:${encodeURIComponent(
      process.env.DATABASE_PASSWORD || "",
    )}@${process.env.DATABASE_HOST || "localhost"}:${process.env.DATABASE_PORT || 3306}/${
      process.env.DATABASE_NAME || ""
    }`,
  },
});
